build: false

platform:
    - x64

image:
    - Visual Studio 2015

environment:
  matrix:
    - CONDA: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      CONDA_ARCH: "64"
      PACKAGE_SUFFIX: "cp36-cp36m"
    - CONDA: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      CONDA_ARCH: "64"
      PACKAGE_SUFFIX: "cp37-cp37m"
    #- CONDA: "C:\\Miniconda38-x64"
    #  PYTHON_VERSION: "3.8"
    #  CONDA_ARCH: "64"
    #  PACKAGE_SUFFIX: "cp38-cp38m"

init:
    - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
    - SET PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;%CONDA%\bin;%PATH%
    - conda info
    - python --version

matrix:
    fast_finish: true

install:
    - conda install cmake perl nasm scikit-build=0.10.0 -y -c conda-forge

build_script:
    - python setup.py bdist_wheel 
    - ls dist/*

test_script:

    # create test env
    - conda create --yes -n test_env python=%PYTHON_VERSION% nose
    - activate test_env
    - conda install pytest jupyter_kernel_test -y -c conda-forge

    # install from wheel
    - pip install dist/xeus_python-0.6.8-%PACKAGE_SUFFIX%-win_amd64.whl

    # run tests from install wheel
    - cd test
    - pytest . -v

