matrix:
  include:
    # Linux builds
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64
    # OSX builds
    - os: osx
      env:
        - PYTHON_VERSION=3.6
    - os: osx
      env:
        - PYTHON_VERSION=3.7
    - os: osx
      env:
        - PYTHON_VERSION=3.8

language: generic

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull $DOCKER_IMAGE;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export CXX=clang++ CC=clang;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-wheels.sh;
    else
      bash ./travis/build-osx-wheel.sh; 
    fi
